%% =========================================================
%  HOST-SIDE END-TO-END LATENCY ANALYSIS
%
%  This script analyses timing data logged from the host-side
%  haptic control pipeline.
%
%  CSV source:
%  device_timing.csv
%
%  Generated by:
%  DeviceAdapter timing logger thread
%
%  Each row corresponds to one matched update cycle where:
%    1) a fresh device-state packet was parsed
%    2) tool state was published into the host pipeline
%    3) the latest haptic wrench was consumed
%    4) a torque command packet was transmitted
%
%  All timestamps are recorded in nanoseconds using
%  std::chrono::steady_clock on the host PC.
%% =========================================================


%% Load CSV timing data
% Columns come directly from DeviceTimingLogMsg
T = readtable("device_timing.csv");


%% =========================================================
% TIMESTAMP DEFINITIONS (from C++ logger)
%
% t_rx_parse_ns
%   Timestamp taken immediately after the newest valid
%   incoming serial packet is parsed inside DeviceAdapter
%
% t_tool_publish_ns
%   Timestamp taken just before publishing the fresh
%   ToolStateMsg into the host-side messaging pipeline
%
% t_wrench_consume_ns
%   Timestamp taken when the newest haptic wrench command
%   is consumed from the device command channel
%
% t_tx_start_ns
%   Timestamp immediately before sending the torque packet
%   over serial to the MCU
%
% t_tx_done_ns
%   Timestamp immediately after sendRaw() returns
%% =========================================================


%% =========================================================
% DERIVED LATENCY METRICS
%% =========================================================

% ---------------------------------------------------------
% Total host-side end-to-end latency
%
% Measures total host processing delay from:
%   fresh sensor packet parsed
% to:
%   torque packet transmission complete
%
% This is the main reported host-side latency metric
%
% T_host,e2e = t_tx_done - t_rx_parse
% ---------------------------------------------------------
host_e2e_ms = (T.t_tx_done_ns - T.t_rx_parse_ns) / 1e6;


% ---------------------------------------------------------
% Tool-state publish delay
%
% Measures delay from:
%   successful packet parse
% to:
%   publishing into host pipeline
%
% Captures:
%   parser + state update + pose conversion cost
% ---------------------------------------------------------
publish_ms = (T.t_tool_publish_ns - T.t_rx_parse_ns) / 1e6;


% ---------------------------------------------------------
% Host pipeline / queue delay
%
% Measures delay from:
%   tool state publish
% to:
%   haptic wrench consume
%
% Captures:
%   thread scheduling
%   channel delay
%   haptic engine computation delay
% ---------------------------------------------------------
pipeline_ms = (T.t_wrench_consume_ns - T.t_tool_publish_ns) / 1e6;


% ---------------------------------------------------------
% Serial transmit duration
%
% Measures duration of the serial write itself
%
% T_tx = t_tx_done - t_tx_start
% ---------------------------------------------------------
tx_ms = (T.t_tx_done_ns - T.t_tx_start_ns) / 1e6;


%% =========================================================
% SUMMARY STATISTICS
%% =========================================================

fprintf("========================================\n");
fprintf("HOST-SIDE END-TO-END LATENCY\n");
fprintf("========================================\n");

fprintf("Mean: %.4f ms\n", mean(host_e2e_ms));
fprintf("Std:  %.4f ms\n", std(host_e2e_ms));
fprintf("P95:  %.4f ms\n", prctile(host_e2e_ms,95));
fprintf("P99:  %.4f ms\n", prctile(host_e2e_ms,99));

fprintf("\n");

fprintf("Publish delay mean:  %.4f ms\n", mean(publish_ms));
fprintf("Pipeline delay mean: %.4f ms\n", mean(pipeline_ms));
fprintf("TX duration mean:    %.4f ms\n", mean(tx_ms));


%% =========================================================
% PLOT: TOTAL HOST LATENCY DISTRIBUTION
%% =========================================================

figure;
histogram(host_e2e_ms, 50);

xlabel("Host end-to-end latency (ms)");
ylabel("Count");
title("Host-side end-to-end latency distribution");

grid on;


%% =========================================================
% OPTIONAL EXTRA PLOTS
%% =========================================================

figure;
histogram(pipeline_ms, 50);
xlabel("Pipeline delay (ms)");
ylabel("Count");
title("Tool publish to wrench consume delay");
grid on;

figure;
histogram(tx_ms, 50);
xlabel("Serial TX duration (ms)");
ylabel("Count");
title("Torque packet transmit duration");
grid on;